repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/prettier/prettier
    rev: '2.1.2'
    hooks:
      - id: prettier
        entry: prettier --write --single-quote --trailing-comma=all
        files: "\\.(\
          css|less|scss\
          |graphql|gql\
          |js|jsx\
          |json\
          |md|markdown|mdown|mkdn\
          |mdx\
          |ts|tsx\
          |yaml|yml\
          )$"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
